# 예외 처리

## 예외와 예외 처리 클래스

자바에는 에러뿐만 아니라 예외라는 오류가 있다. 에러는 컴퓨터 하드웨어의 오동작 또는 고장으로 인해 응용프로그램 실행 오류가 발생하는 것이다. 예외는 사용자의 잘못된 동작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류이다.
에러나 예외나 발생하면 프로그램이 종료된다는 점은 같다. 다만 예외는 예외 처리를 통해 프로그램을 종료하지 않고 정상 실행 상태가 유지되도록 할 수 있다.

예외는 일반 예외, 실행 예외 두 가지가 있다.

- 일반 예외는 컴파일러 체크 예외라고도 하는데, 자바 소스를 컴파일하는 과정에서 검사하기 때문이다.
- 실행 예외는 컴파일하는 과정에서 예외 처리 코드를 검사하지 않는 예외를 말한다.

컴파일 시 예외 처리를 확인하는 부분에만 차이가 있을 뿐, 둘 다 예외 처리가 필요하다.

자바는 예외를 클래스로 관리한다. 모든 예외 클래스들은 java.lan.Exception 클래스를 상속받는다.

실행 예외는 일반 예외와 달리 RuntimeException 을 상속받는 클래스들이다.

## 실행 예외

실행 예외는 자바 컴파일러가 체크를 하지 않기 때문에 오로지 개발자의 경험에 의해서 예외 처리 코드를 삽입해야 한다. (만약 실행 예외에 대해 예외 처리 코드를 넣지 않았을 경우, 해당 예외가 발생하면 프로그램은 종료된다.)
자바 프로그램에서 자주 발생하는 실행 예외를 나열하겠다. 언제 발생하고 어떤 오류 메시지를 출력하는지 잘 알아둬야 한다.

### NullPointerException

자바 프로그램에서 가장 빈번하게 발생하는 실행 예외는 `java.lang.NullPointerException`일 것이다. 이것은 객체 참조가 없는 상태인 null 값을 가지는 참조 변수로 객체 접근 연산자 `.`를 사용했을 때 발생한다.
즉 객체가 없는 상태에서 객체를 사용하려 했기 때문에 발생한 실행 예외이다.

```java
public class NullPointerExceptionExample {
    public static void main(String[] args) {
        String data = null;
        System.out.println(data.toString());
    }
}
```

### ArrayIndexOutOfBoundsException

배열에서 인덱스 범위를 초과하여 사용할 경우 실행 예외 `java.lang.ArrayIndexOutOfBoundsException`이 발생한다.

```java
public class ArrayIndexOutOfBoundsExceptionExample {
    public static void main(String[] args) {
        String data1 = args[0];
        String data2 = args[1];

        System.out.println("args[0]: " + data1);
        System.out.println("args[1]: " + data2);
    }
}
```

에러를 해결하려면 배열의 값을 읽기 전에 배열 길이를 먼조 조사해야 한다.

```java
public class ArrayIndexOutOfBoundsExceptionExample {
    public static void main(String[] args) {
        if (args.length == 2) {
            String data1 = args[0];
            String data2 = args[1];
            System.out.println("args[0]: " + data1);
            System.out.println("args[1]: " + data2);
        } else {
            System.out.println("[실행 방법]");
            System.out.print("java ArrayIndexOutOfBoundsExceptionExample ");
            System.out.print("값 1 값 2");
        }

    }
}
```

### NumberFormaException

문자열을 정수로 반환하는 `Integer.parseInt(String s)`, 실수로 반환하는 `Double.parseDouble(String s)`에서 숫자로 변환할 수 없는 문자가 포함되어 있을 때 `java.lang.NumberFormatException`이 발생한다.

```java
public class NumberFormatExceptionExample {
    public static void main(String[] args) {
        String data1 = "100";
        String data2 = "a100";

        int value1 = Integer.parseInt(data1);
        int value2 = Ineger.parseInt(data2); // NumberFormatException
    }
}
```

### ClassCastException

타입 변환(Casting)은 상위 클래스와 하위 클래스, 구현 클래스와 인터페이스 간에 발생한다. 이런 관계가 아님에도 억지로 타입 변환을 시도하면 ClassCastException 이 발생한다.
ClassCastException 을 막으려면 타입 변환 전에 `instanceof` 연산자로 확인하는 것이 좋다.

```java
class Animal {}
class Dog extends Animal {}
class Cate extends Animal {}
```

```java
public class ClassCastExceptionExample {
    public static void main(String[] args) {
        Dog dog = new Dog();
        changeDog(dog);

        Cat cat = new Cat();
        changeDog(cat); // not Dog
    }
    public static void changeDog(Animal animal) {
        if (animal instanceof Dog) {
            Dog dog = (Dog) animal;
        } else { System.out.println("not Dog"); }
    }
}
```

## 예외 처리 코드

프로그램에서 예외가 발생했을 경우 프로그램의 갑작스러운 종료를 막고, 정상 실행을 유지할 수 있도록 처리하는 코드를 예외 처리 코드라고 한다.
자바 컴파일러는 소스 파일을 컴파일할 때 일반 예외가 발생할 가능성이 있는 코드가 있으면 컴파일 오류를 발생시켜서 개발자가 예외 처리 코드를 작성하도록 요구한다. 하지만 실행 예외는 컴파일러가 체크해주지 않아 직접 작성해야 한다.

예외 처리 코드는 `try-catch-finally` 블록을 이용한다.

- 정상 작동 시 : try 실행 -> finally 실행
- 예외 발생 시 : try 실행 -> 예외 발견, catch 실행 -> finally 실행

일반 예외 처리

```java
public class TryCatchFinallyExample {
    public static void main(String[] args) {
        try {
            // forName : 매가값의 이름을 가진 클래스가 있으면 그 클래스의 객체를 리턴. 없으면 예외 발생.
            Class clazz = Class.forName("java.lang.String2");
        } catch (ClassNotFoundException e) { System.out.println("해당하는 클래스가 존재하지 않는다."); }
    }
}
// java.lang.String2 클래스가 없어서 예외가 발생한다.
```

실행 예외 처리

```java
public class TryCatchFinallyRuntimeExceptionExample {
    public static void main(String[] args) {
        String data1 = null;
        String data2 = null;
        try {
            data1 = arags[0];
            data2 = args[1];
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("실행 매개값의 수가 부족하다.");
            System.out.println("[실행 방법]");
            System.out.println("java TryCatchFinallyRuntimeExceptionExample num1 num2");
            return;
        }

        try {
            int value1 = Integer.parseInt(data1);
            int value2 = Integer.parseInt(data2);
            int result = value1 + value2;
        } catch(NumberFormatException e) {
            System.out.println("NumberFormatException");
        } finally {
            System.out.println("다시 실행하시오.");
        }
    }
}
```

## 예외 종류에 따른 처리 코드

### 다중 catch

try 블록 내부는 다양한 종류의 예외가 발생할 수 있다. 이럴 때 다중 catch 블록을 작성한다.

```java
public class CatchByExceptionKindExample {
    public static void main(String[] args) {
        try {
            String data1 = args[0];
            String data2 = args[1];
            int value1 = Integer.parseInt(data1);
            int value2 = Integer.parseInt(data2);
            int result = value1 + value2;
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("ArrayIndexOutOfBoundsException");
        } catch(NumberFormatException e) {
            System.out.println("NumberFormatException");
        } finally {
            System.out.println("다시 실행하시오.");
        }
    }
}
```

### catch 순서

다중 catch 블록을 작성할 때 주의할 점은 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다. 만약 그렇지 않을 경우, 하위 예외 클래스의 catch 블록은 실행되지 않는다.

```java
try {
    // ...
} catch (ArrayIndexOutOfBoundsException e) {
    System.out.println("하위 예외 클래스");
} catch(Exception e) {
    System.out.println("상위 예외 클래스");
}
```

### 멀티 catch

자바7부터 하나의 catch 블록에서 여러 개의 예외 처리를 할 수 있도록 멀티 catch 를 추가했다.

```java
try {
    // ...
} catch(ArrayIndexOutOfBoundsException | NumberFormatException) {
    System.out.println("ArrayIndexOutOfBoundsException 또는 NumberFormatException");
}
```

## 자동 리소스 닫기

자바7부터 새로 추가된 `try-with-resources` 를 사용하면 예외 발생 여부와 상관없이 사용했던 리소스 객체(각종 입출력 스트림, 서버 소켓, 소켓, 각종 채널)의 close() 메소드를 호출해서 안전하게 리소스를 닫는다.

예를 들어 파일의 데이터를 읽는 `FileInputStream` 객체와 파일에 쓰는 `FileOutputStream`은 리소스 객체로, 안전하게 닫는 과정이 필요하다.

```java
// 이전의 닫기
try {
    fis = new FileInputStream("file.txt");
    // ...
} catch (IOException e) {
    // ...
} finally {
    if (fis != null) {
        try {
            fis.close();
        } catch (IOException e) {}
    }
}

// try-with-resources
try(FileInputStream fis = new FileInputStream("file.txt")) {
    // ...
} catch (IOException e) {
    // ...
}

// 여러 개의 리소스일 경우
try(
    FileInputStream fis = new FileInputStream("file.txt");
    FileOutputStream fos = new FileOutputStream("file2.txt")
) {
    // ...
} catch (IOException e) {
    // ...
}
```

`try-with-resources` 을 사용하려면 리소스 객체가 `java.lang.AutoCloseable` 인터페이스를 구현하고 있어야 한다. `try-with-resources`는 AutoCloseable 인터페이스의 close() 메소드를 자동 호출하기 때문이다.

```java
public class FileInputStream implements AutoCloseable {
    private String file;

    public FileInputStream(String file) {
        this.file = file;
    }
    public void read() { System.out.println("read " + file); }
    @Override
    public void close() throws Exception { System.out.println("close " + file); }
}
```

```java
public class TryWithResourceExample {
    public static void main(String[] args) {
        try (FileInputStream fis = new FileInputStream("file.txt")) {
            fis.read(); // read file.txt
            // 강제로 예외 발생시키기
            throw new Exception(); // close file.txt
        } catch (Exception e) { System.out.println("예외 처리 코드 실행"); }
    }
}
```

## 예외 떠넘기기

try-catch 블록으로 예외를 처리하는 것이 기본인데, 경우에 따라서는 메소드를 호출한 곳으로 예외를 떠넘길 수 있다. 메소드 선언부 끝에 throws 키워드를 작성해 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠넘길 수 있다.
발생할 수 있는 예외의 종류별로 throws 뒤에 나열하는 것이 일반적이지만, `throws Exception`으로 모든 예외를 간단히 떠넘길 수 있다.

throws 키워드가 붙은 메소드는 반드시 try 블록 내에서 호출되어야 한다. 그리고 catch 블록에서 떠넘겨 받은 예외를 처리해야 한다.
또는 throws 를 다시 사용해 예외를 호출한 곳으러 떠넘긴다.

```java
public class ThrowsExample {
    public static void main(String[] args) {
        try {
            findClass();
        } catch (ClassNotFoundException e) { System.out.println("클래스가 존재하지 않는다."); }
    }

    public static void findClass() throws ClassNotFoundException {
        Class clazz = Class.forName("java.lang.String2");
    }
}
```

main() 메소드에서 throws 키워드를 사용하면 JVM 이 최종적으로 예외 처리를 하게 된다. 다만 main() 메소드에 throws Exception 을 붙이는 것은 좋은 예외 처리 방법이 아니다. 프로그램 사용자는 프로그램이 알 수 없는 예외 내용을 출력하고 종료되는 것을 좋아하지 않는다. 따라서 main() 에서 try-catch 블록으로 예외를 처리하는 것이 좋다.

## 사용자 정의 예외와 예외 발생

애플리케이션 서비스와 관련된 예외를 애플리케이션 예외라 하는데, 개발자가 직접 정의해서 만들어야 하므로 사용자 정의 예외라고도 한다.

### 사용자 정의 예외 클래스 선언

사용자 정의 예외 클래스는 컴파일러가 체크하는 일반 예외 또는 체크하지 않는 실행 예외로 선언할 수 있다. 일반 예외로 선언하려면 Exception 을 상속하고, 실행 예외로 선언하려면 RuntimeException 을 상속하면 된다.
사용자 정의 예외 클래스의 이름은 "~Exception"으로 끝나는 것이 좋다.

사용자 정의 예외 클래스도 필드, 생성자, 메소드 선언들을 포함할 수 있지만 대부분 생성자 선언만을 포함한다. 두 개의 생성자를 선언하는 것이 일반적인데, 하나는 매개변수가 없는 기본 생성자, 다른 하나는 예외 발생의 원인을 전달하는 String 타입의 매개변수를 가진 생성자이다.
String 매개변수를 가진 생성자는 상위 클래스의 생성자를 호출해 예외 메시지를 넘겨준다.

```java
public class BalanceInsufficientException extends Exception {
    public BalanceInsufficientException() {}
    public BalanceInsufficientException(String message) {
        super(message);
    }
}
```

### 예외 발생시키기

`throw new XXXException();`, `throw new XXXException("메시지");` 형식으로 예외를 발생시킨다.

예외 객체를 생성할 때는 기본 생성자나 예외 메시지 생성자 어느 것이든 상관없다. 만약 catch 블록에서 예외 메시지가 필요하다면 예외 메시지 생성자를 이용해야 한다.
예외 발생 코드를 가진 메소드는 내부에서 try-catch 블록으로 예외 처리를 할 수 있지만, 대부분 자신을 호출한 곳에서 예외를 처리하도록 throws 키워드로 예외를 떠넘긴다.

```java
public class Account {
    private long balance;

    public Account() {}

    public long getBalance() { return balance; }
    public void deposit(int money) { balance += money; }
    // 사용자 정의 예외 떠넘기기
    public void withdraw(int money) throws BalanceInsufficientException {
        if (balance < money) {
            // 사용자 정의 예외 발생
            throw new BalanceInsufficientException("잔고 부족: " + (money - balance) + "원이 모자람");
        }
        balance -= money;
    }
}
```

## 예외 정보 얻기

모든 예외 객체는 Exception 클래스를 상속하기 때문에 Exception 이 가지고 있는 메소드를 모든 예외 객체에서 호출할 수 있다. 그중 가장 많이 사용하는 메소느는 getMessage(), printStackTrace() 이다.
예외를 발생시킬 때 String 타입의 메시지 생성자를 이용했다면, 그 메시지는 자동적으로 예외 객체 내부에 저장된다. 예외 메시지는 catch 블록에서 getMessage() 메소드의 리턴값으로 얻을 수 있다.
printStackTrace() 메소드는 예외 발생 코드를 추척해서 모두 콘솔에 출력한다. 어떤 예외가 어디에서 발생했는지 상세하게 출력해준다.

```java
public class AccountExample {
    public static void main(String[] args) {
        Account account = new Account();
        // 예금하기
        account.deposit(10000);
        System.out.println("예금액: " + account.getBalance());
        // 출금하기
        try {
            account.withdraw(30000);
        } catch (BalanceInsufficientException e) {
            String message = e.getMessage();
            System.out.println(message);
            System.out.println();
            e.printStackTrace();
        }
    }
}
'''
예금액: 10000
잔고부족: 20000 모자람

BalanceInsufficientException: 잔고부족: 20000 원이 모자람
        at Account.withdraw(Account.java:16)
        at AccountExample.main(AccountExample.java:9)
'''
```
